namespace TextFx
{
	public enum ANIMATION_DATA_TYPE
	{
		NONE,
		ALL,
		TEXT_CHANGED,
		ANIMATE_ON,
		ACTION_TYPE,
		LETTER_ANCHOR,
		EASE_TYPE,
		COLOUR,
		POSITION,
		LOCAL_ROTATION,
		GLOBAL_ROTATION,
		LOCAL_SCALE,
		GLOBAL_SCALE,
		FORCE_SAME_START,
		WHITE_SPACES_DELAYS,
		DELAY,
		DURATION,
		AUDIO_EFFECTS,
		PARTICLE_EFFECTS,
		DELAY_EASED_RANDOM_SWITCH,
		NUM_LOOP_ITERATIONS
	}
}
